service: node-express-lambda

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1

  apiKeys:
    - nodeExpressKey

functions:
  app:
    handler: app.awsLambdaHandler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
          private: true
  
